# frozen_string_literal: true

# TODO introduce an autoloader

require_relative "./draw/custom_shape"
require_relative "./draw/enhanced_geometry"
require_relative "./draw/frame"
require_relative "./draw/image"
require_relative "./draw/page"
require_relative "./office/automatic_styles"
require_relative "./office/body"
require_relative "./office/document_content"
require_relative "./office/document_meta"
require_relative "./office/document_styles"
require_relative "./office/meta"
require_relative "./office/presentation"
require_relative "./office/styles"
require_relative "./dc/title"
require_relative "./dc/description"
require_relative "./meta/generator"
require_relative "./meta/editing_cycles"
require_relative "./meta/keyword"
require_relative "./meta/user_defined"
require_relative "./presentation/notes"
require_relative "./presentation/settings"
require_relative "./style/drawing_page_properties"
require_relative "./style/fill_image"
require_relative "./style/graphic_properties"
require_relative "./style/master_page"
require_relative "./style/paragraph_properties"
require_relative "./style/text_properties"
require_relative "./style/style_node"
require_relative "./table/table_cell"
require_relative "./table/table_row"
require_relative "./table/table"
require_relative "./text/line_break"
require_relative "./text/link"
require_relative "./text/list_item"
require_relative "./text/list"
require_relative "./text/paragraph"
require_relative "./text/plain_text"
require_relative "./text/space"
require_relative "./text/span"
require_relative "./text/text_box"